!macro CLASHNOVA_STOP_INSTALLED_PROCESSES
  DetailPrint "Stopping running ClashNova processes..."
  nsExec::ExecToLog `powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "& { $$ErrorActionPreference = 'SilentlyContinue'; $$installRoot = [System.IO.Path]::GetFullPath('$INSTDIR').TrimEnd([System.IO.Path]::DirectorySeparatorChar, [System.IO.Path]::AltDirectorySeparatorChar); $$installDir = $$installRoot + [System.IO.Path]::DirectorySeparatorChar; $$appNames = @('ClashNova.exe', 'clashnova.exe'); $$lockTargets = @((Join-Path $$installRoot 'helpers\clashnova-service.exe'), (Join-Path $$installRoot 'helpers\mihomo.exe'), (Join-Path $$installRoot 'service\clashnova-service.exe'), (Join-Path $$installRoot 'mihomo.exe'), (Join-Path $$installRoot 'mihomo-x86_64-pc-windows-msvc.exe'), (Join-Path $$installRoot 'clashnova.exe')); function Stop-Targets { $$svcInfo = Get-CimInstance Win32_Service -Filter ""Name='clashnova-core'""; if($$svcInfo) { if($$svcInfo.ProcessId -and $$svcInfo.ProcessId -ne 0) { & taskkill.exe /PID $$svcInfo.ProcessId /T /F | Out-Null }; & sc.exe stop clashnova-core | Out-Null; Stop-Service -Name 'clashnova-core' -Force -ErrorAction SilentlyContinue }; foreach($$name in $$appNames) { & taskkill.exe /IM $$name /T /F | Out-Null }; $$all = @(Get-CimInstance Win32_Process); $$hits = @($$all | Where-Object { $$path = $$_.ExecutablePath; $$cmd = $$_.CommandLine; ($$path -and ([System.IO.Path]::GetFullPath($$path)).StartsWith($$installDir, [System.StringComparison]::OrdinalIgnoreCase)) -or ($$cmd -and $$cmd.IndexOf($$installDir, [System.StringComparison]::OrdinalIgnoreCase) -ge 0) }); foreach($$p in $$hits) { & taskkill.exe /PID $$p.ProcessId /T /F | Out-Null } }; function Test-Unlocked($$path) { if(-not (Test-Path $$path)) { return $$true }; try { $$fs = [System.IO.File]::Open($$path, [System.IO.FileMode]::Open, [System.IO.FileAccess]::ReadWrite, [System.IO.FileShare]::None); $$fs.Close(); return $$true } catch { return $$false } }; for($$i = 0; $$i -lt 120; $$i++) { Stop-Targets; $$locked = @($$lockTargets | Where-Object { -not (Test-Unlocked $$_) }); $$svc = Get-Service -Name 'clashnova-core' -ErrorAction SilentlyContinue; if($$locked.Count -eq 0 -and (-not $$svc -or $$svc.Status -eq 'Stopped')) { break }; Start-Sleep -Milliseconds 250 }; & sc.exe delete clashnova-core | Out-Null; Stop-Targets }"`
  Sleep 1600
!macroend

!macro CLASHNOVA_REMOVE_STALE_UNINSTALL_ENTRIES
  DetailPrint "Cleaning stale ClashNova uninstall entries..."
  nsExec::ExecToLog `powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "& { $$ErrorActionPreference = 'SilentlyContinue'; $$roots = @('HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall', 'HKLM:\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall', 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall', 'HKCU:\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall'); function Get-ClashNovaEntries { foreach($$root in $$roots) { if(Test-Path $$root) { Get-ChildItem -LiteralPath $$root | ForEach-Object { $$props = Get-ItemProperty -LiteralPath $$_.PSPath; if($$props.DisplayName -eq 'ClashNova') { [pscustomobject]@{ Key = $$_.PSPath; UninstallString = $$props.UninstallString; QuietUninstallString = $$props.QuietUninstallString; WindowsInstaller = $$props.WindowsInstaller } } } } } }; function Invoke-EntryUninstall($$entry) { $$cmd = $$entry.QuietUninstallString; if([string]::IsNullOrWhiteSpace($$cmd)) { $$cmd = $$entry.UninstallString }; if([string]::IsNullOrWhiteSpace($$cmd)) { return }; $$guid = [regex]::Match($$cmd, '\{[0-9A-Fa-f-]{36}\}'); if($$entry.WindowsInstaller -eq 1 -or $$cmd -match 'MsiExec' -or $$guid.Success) { if($$guid.Success) { Start-Process -FilePath 'msiexec.exe' -ArgumentList @('/x', $$guid.Value, '/qn', '/norestart') -Wait -WindowStyle Hidden }; return }; $$exe = $$null; $$args = ''; if($$cmd -match '^\s*""([^""]+)""\s*(.*)$$') { $$exe = $$Matches[1]; $$args = $$Matches[2] } else { $$parts = $$cmd.Trim() -split '\s+', 2; $$exe = $$parts[0]; if($$parts.Count -gt 1) { $$args = $$parts[1] } }; if($$exe -and (Test-Path $$exe)) { if($$args -notmatch '(^|\s)/S(\s|$$)') { $$args = ($$args + ' /S').Trim() }; Start-Process -FilePath $$exe -ArgumentList $$args -Wait -WindowStyle Hidden } }; foreach($$entry in @(Get-ClashNovaEntries)) { Invoke-EntryUninstall $$entry }; Start-Sleep -Milliseconds 500; foreach($$entry in @(Get-ClashNovaEntries)) { Remove-Item -LiteralPath $$entry.Key -Recurse -Force } }"`
!macroend

!macro NSIS_HOOK_PREINSTALL
  !insertmacro CLASHNOVA_STOP_INSTALLED_PROCESSES
  !insertmacro CLASHNOVA_REMOVE_STALE_UNINSTALL_ENTRIES
  !insertmacro CLASHNOVA_STOP_INSTALLED_PROCESSES
!macroend

!macro NSIS_HOOK_PREUNINSTALL
  !insertmacro CLASHNOVA_STOP_INSTALLED_PROCESSES
!macroend
